### ISSUE TITLE
建议使用 branch

### ISSUE THREAD

**Issue by tandf** [Lukeming-tsinghua/pytorch-NLP-guidance#1]
太强啦陆！

其实用 branch 比较方便，每个人一个 branch ，这样 push 的时候不用先 pull 别人的更改。最后交上作业再 merge 即可。

**Comment by Lukeming-tsinghua** [comment]
Thanks for your significant advice!

I will enforce the branch management as soon as everybody is skilled in git.

**Comment by tandf** [comment]
Great! Go lulu!
